### ISSUE TITLE
show your work in DDC Working Group

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/IGiS#50]
Hi, this project is really cool and interesting!
There are some common areas (collaboration, identity, ...) that we are also working on.
I'd love you people to participate in the Dynamic Data and Capabilities Working Group and tell us about your project.
Next one is today: https://github.com/ipfs/dynamic-data-and-capabilities/issues/39
Would you be up for that?

**Comment by dirkmc** [comment]
@pgte sure, that sounds interesting, thank you for the invitation
I see the meeting is at 4pm CET. I just want to confirm: is it CET or CEST?
I'm not sure if @magik6k will be available but I'm happy to talk about the project if he is not.

**Comment by pgte** [comment]
@dirkmc thank you for showing up and demoing IGis!
Here is [the video](https://www.youtube.com/watch?v=EiJE59uYNAk) and [the nodes](https://github.com/ipfs/dynamic-data-and-capabilities/issues/39#issuecomment-422491889)
